CREATE TABLE platform_providers (
    provider text PRIMARY KEY,
    channel text NOT NULL,
    description text NOT NULL DEFAULT '',
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO platform_providers (provider, channel, description) VALUES
('mock_email','email','Mock email provider for local testing'),
('smtp','email','SMTP email delivery via net/smtp'),
('sendgrid','email','SendGrid email API (placeholder)'),
('ses','email','Amazon SES email (placeholder)'),
('mailgun','email','Mailgun email API (placeholder)'),
('postmark','email','Postmark transactional email API (placeholder)'),
('brevo','email','Brevo transactional email API (placeholder)'),
('mailjet','email','Mailjet email API (placeholder)'),
('sparkpost','email','SparkPost email API (placeholder)'),
('resend','email','Resend email API (placeholder)'),
('mandrill','email','Mailchimp Transactional email API (placeholder)'),
('mock_sms','sms','Mock SMS provider for local testing'),
('generic_http_sms','sms','Generic HTTP SMS gateway'),
('sparrow','sms','Sparrow SMS gateway'),
('twilio','sms','Twilio SMS API (placeholder)'),
('aakash_sms','sms','Aakash SMS gateway (placeholder)'),
('quickconnect','sms','QuickConnect SMS gateway (placeholder)'),
('bangalink','sms','BanglaLink SMS gateway (placeholder)'),
('ncell','sms','Ncell SMS gateway (placeholder)'),
('ntc','sms','Nepal Telecom SMS gateway (placeholder)'),
('infobip','sms','Infobip SMS API (placeholder)'),
('messagebird','sms','MessageBird SMS API (placeholder)'),
('vonage','sms','Vonage SMS API (placeholder)'),
('plivo','sms','Plivo SMS API (placeholder)'),
('telnyx','sms','Telnyx SMS API (placeholder)'),
('sinch','sms','Sinch SMS API (placeholder)'),
('mock_fcm','fcm','Mock FCM provider for local testing'),
('fcm','fcm','Firebase Cloud Messaging HTTP v1'),
('apns','fcm','Apple Push Notification service adapter (placeholder)'),
('onesignal','fcm','OneSignal push notification API (placeholder)'),
('expo','fcm','Expo push notification service (placeholder)'),
('hms_push','fcm','Huawei Mobile Services push kit (placeholder)'),
('websocket','websocket','Internal WebSocket provider'),
('pusher','websocket','Pusher Channels real-time messaging (placeholder)'),
('ably','websocket','Ably real-time messaging (placeholder)'),
('socketio','websocket','Socket.IO real-time gateway (placeholder)'),
('in_app','in_app','In-app notification store'),
('database_inbox','in_app','Database-backed in-app notification inbox (placeholder)'),
('whatsapp_cloud','whatsapp','WhatsApp Cloud API (placeholder)'),
('twilio_whatsapp','whatsapp','Twilio WhatsApp API (placeholder)'),
('messagebird_whatsapp','whatsapp','MessageBird WhatsApp API (placeholder)'),
('viber_business','viber','Viber Business Messages API (placeholder)'),
('telegram_bot','telegram','Telegram Bot API (placeholder)'),
('slack','slack','Slack messaging API (placeholder)'),
('teams','teams','Microsoft Teams messaging API (placeholder)'),
('web_push_vapid','web_push','Browser Web Push with VAPID (placeholder)'),
('onesignal_web_push','web_push','OneSignal browser push API (placeholder)')
ON CONFLICT (provider) DO UPDATE SET
    channel = EXCLUDED.channel,
    description = EXCLUDED.description,
    updated_at = now();

CREATE INDEX idx_platform_providers_channel ON platform_providers(channel, provider);
